ALTER TABLE  EDG_SPACES ADD (EXT_LINK_TYPE number(10,0));
UPDATE EDG_SPACES SET EXT_LINK_TYPE=0;
alter table EDG_PAGES_PROGRESS ADD COLUMN LINK_EXTRA_INFO long;
alter table EDG_PAGES_PROGRESS ADD COLUMN LINK_EXTRA_ID varchar2(255 char);
create index LINK_EXTRA_ID_INDEX on EDG_PAGES_PROGRESS (LINK_EXTRA_ID);
alter table EDG_DRAFTS ADD COLUMN PROGRESS_PUID number(10,0);
alter table EDG_DRAFTS add constraint FK23881789FCC23A06 foreign key (PROGRESS_PUID) references EDG_PAGES_PROGRESS;
