ALTER TABLE EDG_ROLES ADD  (CREATOR_PUID number(10,0));
ALTER TABLE EDG_ROLES ADD  (MODIFIER_PUID number(10,0));
ALTER TABLE EDG_ROLES ADD  (CREATED_DATE timestamp);
ALTER TABLE EDG_ROLES ADD  (MODIFIED_DATE  timestamp);