alter table EDG_SPACES ADD COLUMN EXT_LINK_TYPE integer;
update EDG_SPACES set EXT_LINK_TYPE=0;
alter table EDG_PAGES_PROGRESS ADD COLUMN LINK_EXTRA_INFO longtext;
alter table EDG_PAGES_PROGRESS ADD COLUMN LINK_EXTRA_ID varchar(255);
 create index LINK_EXTRA_ID_INDEX on EDG_PAGES_PROGRESS (LINK_EXTRA_ID);
alter table EDG_DRAFTS ADD COLUMN PROGRESS_PUID integer;
alter table EDG_DRAFTS add index FK23881789FCC23A06 (PROGRESS_PUID), add constraint FK23881789FCC23A06 foreign key (PROGRESS_PUID) references EDG_PAGES_PROGRESS (PUID);